### ISSUE TITLE
Don't think it's still possible to check if account is closed [Twitch API]

### ISSUE THREAD

**Issue by jaylane** [Rafase282/My-FreeCodeCamp-Code#30]
I'm working on this project now and since it is suggested to use the third party api in lieu of registering for a twitch.tv api key, I don't think one of the user stories works now. The json response for one of the suggested closed account users (comster404)  is as follows:

{"stream":null,"_links":{"self":"https://api.twitch.tv/kraken/streams/comster404","channel":"https://api.twitch.tv/kraken/channels/comster404"}}

this is the same response as an active offline account, so I don't see a way to distinguish between the two.

**Comment by kjuchtmans** [comment]
I concur. Who has a valid workaround for this?

**Comment by Rafase282** [comment]
I took a look and now I wonder if they changed the API altogether, my app does not work anymore.

Edit: I Found the reason:

```
UPDATE: Due to a change in conditions on API usage explained here Twitch.tv now requires an API key, but we've built a workaround. Use https://wind-bow.gomix.me/twitch-api instead of twitch's API base URL (i.e. https://api.twitch.tv/kraken ) and you'll still be able to get account information, without needing to sign up for an API key.
```

**Comment by Rafase282** [comment]
I tried the alternate API and it seems to break a promise or something. This would require a API key or checking the code for the alternate API. 

If I get the key, then I would have to use a server to host it without making it public. 

While I don't feel like solving this at the moment as my hands are full with other things, I can answer your question. Use the `/users/` to check if the user exist or not anymore instead of the streams.

`https://wind-bow.glitch.me/twitch-api/users/comster404`

```json
{
"error": "Not Found",
"status": 404,
"message": "User \"comster404\" was not found"
}
```
